[project]
name = "hacknation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "google-cloud-aiplatform[adk,agent-engines]>=1.128.0",
    "pydantic-ai>=1.27.0",
    "pydantic-settings>=2.12.0",
    "google-generativeai>=0.8.0",
    "pydantic-ai-slim[google]>=1.27.0",
    "python-dotenv>=1.2.1",
]
