[project]
name = "hacknation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-aiplatform[adk,agent-engines]>=1.128.0",
    "pydantic-ai>=1.27.0",
    "pydantic-settings>=2.12.0",
    "google-generativeai>=0.8.0",
    "pydantic-ai-slim[google]>=1.27.0",
    "python-dotenv>=1.2.1",
    "pypdf>=4.0.0",
    "sentence-transformers>=2.2.0",
    "psycopg2-binary>=2.9.0",
    "pgvector>=0.2.0",
    "transformers>=4.30.0",
    "torch>=2.0.0",
]
